GET http://localhost:8000/dinosaurs

###
POST http://localhost:8000/dinosaurs
Content-Type: application/json

{
"title": "Some Random Dino", "desc": "Pick delicious emoji", "types": ["🌲🌲", "🍖🍖", "👏👏"]
}






